#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 14 16:16:21 2021

@author: chess-lin
"""

import spectres
from spectrum import Spectrum

cube_file = '../../data/NGC613/Muse/NGC0613_DATACUBE_FINAL_clean.fits'


#ler cubo
with fits.open(cube_file) as hdu:
    wcs = WCS(hdu[1].header)
    flux_cube = np.nanmax(np.array(hdu[1].data), axis = 0)
    err_cube = np.nanmax(np.array(hdu[2].data), axis = 0)
