[resources]
ppxf_results = ../../data_products/toy_50x50/miles/ppxf

[ifscube]
# conf_path = multi_comp_double_broad.cfg
#conf_path = multi_comp_single_broad.cfg
# conf_path = multi_comp.cfg
conf_path = multi_comp_oiii.cfg
# conf_path = halpha.cfg
