[resources]
ppxf_results = ../../data_products/toy_100x100/MilesAgeMh/ppxf

[ifscube]
# conf_path = multi_comp_double_broad.cfg
conf_path = conf/one_comp_balmer_low_high.cfg
# conf_path = multi_comp.cfg
;conf_path = multi_comp_oiii.cfg
;;conf_path = multi_comp16.cfg
# conf_path = halpha.cfg
remove_input = False
