[resources]
model = ../../data/models/tmpWzZ2t1/Mku1.30Z*.fits
observation = ../../data/NGC613/Muse/NGC0613_DATACUBE_FINAL_clean.fits.gz

[observation]
obs_name = NGC613
redshift = 0.004951

[model]
model_name = miles
# remove leading and trailing zeros (in angstrom)
wave_trim = 0 1.5
lsf = 2.51
sampling = linear

[ppxf]
degree = 12
moments = 4

[output]
output_dir = ${observation:obs_name}_${model:model_name}_ppxf_result
