[resources]
model = ../../data/models/tmpWzZ2t1/Mku1.30Z*.fits
observation = ../../data/toy_10x10.fits

[observation]
obs_name = toy_10x10
redshift = 0.004951
sampling = linear

[model]
model_name = miles
# remove leading and trailing zeros (in angstrom)
wave_trim = 0 1.5
lsf = 2.51
sampling = linear

[ppxf]
moments = 4
degree = 12
clean = False

[output]
output_root = ../../data_products/
output_dir = ${observation:obs_name}/
